FROM python:3.10-slim

WORKDIR /app

COPY requirements-pymol.txt .

RUN pip install --no-cache-dir -r requirements-pymol.txt

COPY src/ src/

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "src/server.py"]
